language: ruby

rvm:
  - 2.2.1

bundler_args: --without development

services:
  - elasticsearch

before_script:
  - cp config/database.yml.travis config/database.yml
  - cp config/chewy.yml.travis config/chewy.yml

script:
  - RAILS_ENV=test bundle exec rake db:setup --trace
  - bundle exec rspec spec

addons:
  code_climate:
    repo_token: 9f45b1759413ec95a994b8cf1adad1fe11e73f28a49f0d036512554a61f1c1ec
