language: ruby

rvm:
  - 2.2.1

bundler_args: --without development

before_script:
  - cp config/database.yml.template config/database.yml
  - cp config/secrets.template.yml config/secrets.yml
  - curl -sSL https://raw.githubusercontent.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=4.10.3 bash

script:
  - RAILS_ENV=test bundle exec rake db:setup --trace
  - bundle exec rspec spec

addons:
  code_climate:
    repo_token: 9f45b1759413ec95a994b8cf1adad1fe11e73f28a49f0d036512554a61f1c1ec